services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: otel-getting-started-application:lastest
    tty: true
    volumes:
      - ./:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5000:5000

  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin

  tutorial:
    image: otel-getting-started-tutorial:latest
    build:
      context: tutorial/
      dockerfile: Dockerfile
    ports:
      - 3000:80