services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: otel-getting-started-application:latest
    tty: true
    volumes:
      - ./labs:/workspace
    ports:
      - 5000:5000

  httpbin:
    image: kennethreitz/httpbin

  tutorial:
    image: otel-getting-started-tutorial:latest
    build:
      context: tutorial/
      dockerfile: Dockerfile
      target: rt
    tty: true
    volumes:
      - ./tutorial:/workspace
    ports:
      - 1313:80