services:
  application:
    image: ghcr.io/JenSeReal/otel-getting-started/application:latest
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./labs:/workspace
    ports:
      - 5000:5000

  httpbin:
    image: kennethreitz/httpbin

  tutorial:
    image:  ghcr.io/JenSeReal/otel-getting-started/tutorial:latest
    build:
      context: tutorial/
      dockerfile: Dockerfile
      target: rt
    tty: true
    volumes:
      - ./tutorial:/workspace
    ports:
      - 1313:80